[profile.default]
src = "src"
out = "out"
solc = "0.8.26"
optimizer = true
optimizer_runs = 8000
via_ir = true
evm_version = "cancun"
libs = ["node_modules", "lib"]

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 120
multiline_func_header = "all"
quote_style = "double"
tab_width = 2
wrap_comments = true

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
ethereumSepolia = "${ETHEREUM_SEPOLIA_RPC_URL}"
arbitrumSepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
baseSepolia = "${BASE_SEPOLIA_RPC_URL}"
optimismSepolia = "${OPTIMISM_SEPOLIA_RPC_URL}"
avalancheFuji = "${AVALANCHE_FUJI_RPC_URL}"

[etherscan]
ethereumSepolia = { key = "${ETHERSCAN_API_KEY}", chain = 11155111 }
arbitrumSepolia = { key = "${ARBISCAN_API_KEY}", chain = 421614 }
baseSepolia = { key = "${BASESCAN_API_KEY}", chain = 84532 }
optimismSepolia = { key = "${OPTIMISTIC_ETHERSCAN_API_KEY}", chain = 11155420 }
avalancheFuji = { key = "${SNOWTRACE_API_KEY}", chain = 43113 }
